name: Daily CI Trigger

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:     # (optional) allows you to run manually
  push:                  # (optional) runs on push too
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print success message
        run: echo "✅ This workflow runs daily!"
