name: 24f2008923@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-check:
    name: 24f2008923@ds.study.iitm.ac.in  # <-- This ensures the run itself shows your email
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Confirm email is in job name
        run: echo "✅ Running job under email name"

